//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTelerik.Resources
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_NOP
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_NOP()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoTelerik.Resources.Resource_NOP", typeof(Resource_NOP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No cumple con los requerimientos de la contraseña..
        /// </summary>
        public static string NoCumpleContraseña
        {
            get
            {
                return ResourceManager.GetString("NoCumpleContraseña", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre
        {
            get
            {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Corto.
        /// </summary>
        public static string NombreCorto
        {
            get
            {
                return ResourceManager.GetString("NombreCorto", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Gerente General.
        /// </summary>
        public static string NombreGerenteGeneral
        {
            get
            {
                return ResourceManager.GetString("NombreGerenteGeneral", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Representante Legal.
        /// </summary>
        public static string NombreRepresentanteLegal
        {
            get
            {
                return ResourceManager.GetString("NombreRepresentanteLegal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo actualizar..
        /// </summary>
        public static string NoSePudoActualizar
        {
            get
            {
                return ResourceManager.GetString("NoSePudoActualizar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo eliminar..
        /// </summary>
        public static string NoSePudoEliminar
        {
            get
            {
                return ResourceManager.GetString("NoSePudoEliminar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo registrar..
        /// </summary>
        public static string NoSePudoRegistrar
        {
            get
            {
                return ResourceManager.GetString("NoSePudoRegistrar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se puede registrar porque ya existe..
        /// </summary>
        public static string NoSePudoRegistrarPorqueYaExiste
        {
            get
            {
                return ResourceManager.GetString("NoSePudoRegistrarPorqueYaExiste", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nro. Doc. Gerente General.
        /// </summary>
        public static string NroDocGerenteGeneral
        {
            get
            {
                return ResourceManager.GetString("NroDocGerenteGeneral", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nro. Doc. Representante Legal.
        /// </summary>
        public static string NroDocRepresentanteLegal
        {
            get
            {
                return ResourceManager.GetString("NroDocRepresentanteLegal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string NuevaContrasena
        {
            get
            {
                return ResourceManager.GetString("NuevaContrasena", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Número Días.
        /// </summary>
        public static string NumeroDias
        {
            get
            {
                return ResourceManager.GetString("NumeroDias", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Número Licencia Municipio.
        /// </summary>
        public static string NumeroLicenciaMunicipio
        {
            get
            {
                return ResourceManager.GetString("NumeroLicenciaMunicipio", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Número Registro Público.
        /// </summary>
        public static string NumeroRegistroPublico
        {
            get
            {
                return ResourceManager.GetString("NumeroRegistroPublico", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Número Ruc.
        /// </summary>
        public static string NumeroRuc
        {
            get
            {
                return ResourceManager.GetString("NumeroRuc", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string OlvidasteTuContrasena
        {
            get
            {
                return ResourceManager.GetString("OlvidasteTuContrasena", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string Orden
        {
            get
            {
                return ResourceManager.GetString("Orden", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Otras Opciones.
        /// </summary>
        public static string OtrasOpciones
        {
            get
            {
                return ResourceManager.GetString("OtrasOpciones", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Otros Datos.
        /// </summary>
        public static string OtrosDatos
        {
            get
            {
                return ResourceManager.GetString("OtrosDatos", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ParametrosGenerales.
        /// </summary>
        public static string ParametrosGenerales
        {
            get
            {
                return ResourceManager.GetString("ParametrosGenerales", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string Pais
        {
            get
            {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Permitir Vacaciones Negativas.
        /// </summary>
        public static string PermitirVacacionesNegativas
        {
            get
            {
                return ResourceManager.GetString("PermitirVacacionesNegativas", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string PlantillaCorreo
        {
            get
            {
                return ResourceManager.GetString("PlantillaCorreo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string Provincia
        {
            get
            {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Puerto.
        /// </summary>
        public static string Puerto
        {
            get
            {
                return ResourceManager.GetString("Puerto", resourceCulture);
            }
        }
        public static string Pagar
        {
            get
            {
                return ResourceManager.GetString("Pagar", resourceCulture);
            }
        }

        public static string Periodos
        {
            get
            {
                return ResourceManager.GetString("Periodos", resourceCulture);
            }
        }

        public static string PermisoMenuCampo
        {
            get
            {
                return ResourceManager.GetString("PermisoMenuCampo", resourceCulture);
            }
        }

        public static string NroDocumento
        {
            get
            {
                return ResourceManager.GetString("NroDocumento", resourceCulture);
            }
        }

        public static string NombrePlanilla
        {
            get
            {
                return ResourceManager.GetString("NombrePlanilla", resourceCulture);
            }
        }

        public static string NombrePuesto
        {
            get
            {
                return ResourceManager.GetString("NombrePuesto", resourceCulture);
            }
        }

        public static string NombreDepartamento
        {
            get
            {
                return ResourceManager.GetString("NombreDepartamento", resourceCulture);
            }
        }

        public static string NombreArea
        {
            get
            {
                return ResourceManager.GetString("NombreArea", resourceCulture);
            }
        }

        public static string NombreSeccion
        {
            get
            {
                return ResourceManager.GetString("NombreSeccion", resourceCulture);
            }
        }

        public static string NoSePudoDarDeBaja
        {
            get
            {
                return ResourceManager.GetString("NoSePudoDarDeBaja", resourceCulture);
            }
        }

        public static string NroAFP
        {
            get
            {
                return ResourceManager.GetString("NroAFP", resourceCulture);
            }
        }

        public static string NombrePermisoSalud
        {
            get
            {
                return ResourceManager.GetString("NombrePermisoSalud", resourceCulture);
            }
        }

        public static string NroPermisoSalud
        {
            get
            {
                return ResourceManager.GetString("NroPermisoSalud", resourceCulture);
            }
        }

        public static string NumeroSueldos
        {
            get
            {
                return ResourceManager.GetString("NumeroSueldos", resourceCulture);
            }
        }

        public static string NumeroCuentaSueldo
        {
            get
            {
                return ResourceManager.GetString("NumeroCuentaSueldo", resourceCulture);
            }
        }

        public static string NumeroCuentaSueldoCTS
        {
            get
            {
                return ResourceManager.GetString("NumeroCuentaSueldoCTS", resourceCulture);
            }
        }

        public static string PrimerApellido
        {
            get
            {
                return ResourceManager.GetString("PrimerApellido", resourceCulture);
            }
        }

        public static string NroDocumentoIdentidad
        {
            get
            {
                return ResourceManager.GetString("NroDocumentoIdentidad", resourceCulture);
            }
        }

        public static string Nacionalidad1
        {
            get
            {
                return ResourceManager.GetString("Nacionalidad1", resourceCulture);
            }
        }

        public static string Nacionalidad2
        {
            get
            {
                return ResourceManager.GetString("Nacionalidad2", resourceCulture);
            }
        }

        public static string PaisNacimiento
        {
            get
            {
                return ResourceManager.GetString("PaisNacimiento", resourceCulture);
            }
        }

        public static string PaisResidencia
        {
            get
            {
                return ResourceManager.GetString("PaisResidencia", resourceCulture);
            }
        }

        public static string Nit
        {
            get
            {
                return ResourceManager.GetString("Nit", resourceCulture);
            }
        }

        public static string Observaciones
        {
            get
            {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }

        public static string ObservacionInicio
        {
            get
            {
                return ResourceManager.GetString("ObservacionInicio", resourceCulture);
            }
        }

        public static string ObservacionFinal
        {
            get
            {
                return ResourceManager.GetString("ObservacionFinal", resourceCulture);
            }
        }

        public static string Puestos
        {
            get
            {
                return ResourceManager.GetString("Puestos", resourceCulture);
            }
        }

        public static string PuestoPadre
        {
            get
            {
                return ResourceManager.GetString("PuestoPadre", resourceCulture);
            }
        }

        public static string NumeroPlazas
        {
            get
            {
                return ResourceManager.GetString("NumeroPlazas", resourceCulture);
            }
        }

        public static string NoSePudoCambiarDePuesto
        {
            get
            {
                return ResourceManager.GetString("NoSePudoCambiarDePuesto", resourceCulture);
            }
        }

        public static string Nacionalidad
        {
            get
            {
                return ResourceManager.GetString("Nacionalidad", resourceCulture);
            }
        }

        public static string NoSePudoCambiarDeContrato
        {
            get
            {
                return ResourceManager.GetString("NoSePudoCambiarDeContrato", resourceCulture);
            }
        }

        public static string NoSePudoCambiarDeSalario
        {
            get
            {
                return ResourceManager.GetString("NoSePudoCambiarDeSalario", resourceCulture);
            }
        }

        public static string NoSePudoCambiarDeEstructura
        {
            get
            {
                return ResourceManager.GetString("NoSePudoCambiarDeEstructura", resourceCulture);
            }
        }

        public static string Prevista
        {
            get
            {
                return ResourceManager.GetString("Prevista", resourceCulture);
            }
        }

        public static string Procedimiento
        {
            get
            {
                return ResourceManager.GetString("Procedimiento", resourceCulture);
            }
        }

        public static string NuevoFlujoDeAprobacion
        {
            get
            {
                return ResourceManager.GetString("NuevoFlujoDeAprobacion", resourceCulture);
            }
        }

        public static string NombreDelFlujo
        {
            get
            {
                return ResourceManager.GetString("NombreDelFlujo", resourceCulture);
            }
        }

        public static string PasosDeAprobacion
        {
            get
            {
                return ResourceManager.GetString("PasosDeAprobacion", resourceCulture);
            }
        }

        public static string Paso
        {
            get
            {
                return ResourceManager.GetString("Paso", resourceCulture);
            }
        }

        public static string NumeroMinimoAprobadores
        {
            get
            {
                return ResourceManager.GetString("NumeroMinimoAprobadores", resourceCulture);
            }
        }

        public static string PasoSiguienteAprobacion
        {
            get
            {
                return ResourceManager.GetString("PasoSiguienteAprobacion", resourceCulture);
            }
        }

        public static string PasoSiguienteDesaprobacion
        {
            get
            {
                return ResourceManager.GetString("PasoSiguienteDesaprobacion", resourceCulture);
            }
        }

        public static string NuevoFlujo
        {
            get
            {
                return ResourceManager.GetString("NuevoFlujo", resourceCulture);
            }
        }

        public static string NoAplica
        {
            get
            {
                return ResourceManager.GetString("NoAplica", resourceCulture);
            }
        }

        public static string NoSePudoActivar
        {
            get
            {
                return ResourceManager.GetString("NoSePudoActivar", resourceCulture);
            }
        }

        public static string NoSePudoInactivar
        {
            get
            {
                return ResourceManager.GetString("NoSePudoInactivar", resourceCulture);
            }
        }

        public static string Planilla
        {
            get
            {
                return ResourceManager.GetString("Planilla", resourceCulture);
            }
        }

        public static string PermisoInformacion
        {
            get
            {
                return ResourceManager.GetString("PermisoInformacion", resourceCulture);
            }
        }

        public static string PoliticaSolicitud
        {
            get
            {
                return ResourceManager.GetString("PoliticaSolicitud", resourceCulture);
            }
        }

        public static string Oscuro
        {
            get
            {
                return ResourceManager.GetString("Oscuro", resourceCulture);
            }
        }

        public static string NombreDelFormulario
        {
            get
            {
                return ResourceManager.GetString("NombreDelFormulario", resourceCulture);
            }
        }

        public static string Obligatorio
        {
            get
            {
                return ResourceManager.GetString("Obligatorio", resourceCulture);
            }
        }

        public static string NivelPuesto
        {
            get
            {
                return ResourceManager.GetString("NivelPuesto", resourceCulture);
            }
        }

        public static string NuevoFormulario
        {
            get
            {
                return ResourceManager.GetString("NuevoFormulario", resourceCulture);
            }
        }

        public static string NuevasSolicitudes
        {
            get
            {
                return ResourceManager.GetString("NuevasSolicitudes", resourceCulture);
            }
        }

        public static string OtrasConfiguraciones
        {
            get
            {
                return ResourceManager.GetString("OtrasConfiguraciones", resourceCulture);
            }
        }

        public static string Numero
        {
            get
            {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }

        public static string OrigenVacaciones
        {
            get
            {
                return ResourceManager.GetString("OrigenVacaciones", resourceCulture);
            }
        }

        public static string OrigenAdicional
        {
            get
            {
                return ResourceManager.GetString("OrigenAdicional", resourceCulture);
            }
        }
        
    }
}
