//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTelerik.Resources
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_DEFG
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_DEFG()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoTelerik.Resources.Resource_DEFG", typeof(Resource_DEFG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Dato requerido.
        /// </summary>
        public static string DatoRequerido
        {
            get
            {
                return ResourceManager.GetString("DatoRequerido", resourceCulture);
            }
        }

        public static string DatosPrincipales
        {
            get
            {
                return ResourceManager.GetString("DatosPrincipales", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DatosFinancieros.
        /// </summary>
        public static string DatosFinancieros
        {
            get
            {
                return ResourceManager.GetString("DatosFinancieros", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Descripcion
        {
            get
            {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string Direccion
        {
            get
            {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Dirección Web.
        /// </summary>
        public static string DireccionWeb
        {
            get
            {
                return ResourceManager.GetString("DireccionWeb", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        public static string Empleado
        {
            get
            {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Empleado.
        /// </summary>
        public static string EntidadFinanciera
        {
            get
            {
                return ResourceManager.GetString("EntidadFinanciera", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar
        {
            get
            {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Empresa.
        /// </summary>
        public static string Empresa
        {
            get
            {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El enlace es inválido, probablemente porque ya fue usado, por favor haz un nuevo cambio de contraseña..
        /// </summary>
        public static string EnlaceInvalidoProbablementePorqueYaFueUsado
        {
            get
            {
                return ResourceManager.GetString("EnlaceInvalidoProbablementePorqueYaFueUsado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Entidad Empresa.
        /// </summary>
        public static string EntidadEmpresa
        {
            get
            {
                return ResourceManager.GetString("EntidadEmpresa", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Correo.
        /// </summary>
        public static string EnviarCorreo
        {
            get
            {
                return ResourceManager.GetString("EnviarCorreo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión o información se encuentra en uso..
        /// </summary>
        public static string ErrorDeConexionInformacionSeEncuentraEnUso
        {
            get
            {
                return ResourceManager.GetString("ErrorDeConexionInformacionSeEncuentraEnUso", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar email..
        /// </summary>
        public static string ErrorEnviarEmail
        {
            get
            {
                return ResourceManager.GetString("ErrorEnviarEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Espere por favor.
        /// </summary>
        public static string EsperePorFavor
        {
            get
            {
                return ResourceManager.GetString("EsperePorFavor", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string EstadoEmpleado
        {
            get
            {
                return ResourceManager.GetString("EstadoEmpleado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado
        {
            get
            {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Estado civil.
        /// </summary>
        public static string EstadoCivil
        {
            get
            {
                return ResourceManager.GetString("EstadoCivil", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Estándar.
        /// </summary>
        public static string Estandar
        {
            get
            {
                return ResourceManager.GetString("Estandar", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Estás a punto de cambiar tu contraseña..
        /// </summary>
        public static string EstasAPuntoDeCambiarTuContrasena
        {
            get
            {
                return ResourceManager.GetString("EstasAPuntoDeCambiarTuContrasena", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Factor Compra Mercado.
        /// </summary>
        public static string FactorCompraMercado
        {
            get
            {
                return ResourceManager.GetString("FactorCompraMercado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Factor Compra Oficial.
        /// </summary>
        public static string FactorCompraOficial
        {
            get
            {
                return ResourceManager.GetString("FactorCompraOficial", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Factor Venta Mercado.
        /// </summary>
        public static string FactorVentaMercado
        {
            get
            {
                return ResourceManager.GetString("FactorVentaMercado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Factor Venta Oficial.
        /// </summary>
        public static string FactorVentaOficial
        {
            get
            {
                return ResourceManager.GetString("FactorVentaOficial", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Cambio.
        /// </summary>
        public static string FechaCambio
        {
            get
            {
                return ResourceManager.GetString("FechaCambio", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial.
        /// </summary>
        public static string FechaInicio
        {
            get
            {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inscripción.
        /// </summary>
        public static string FechaInscripcion
        {
            get
            {
                return ResourceManager.GetString("FechaInscripcion", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Termino.
        /// </summary>
        public static string FechaTermino
        {
            get
            {
                return ResourceManager.GetString("FechaTermino", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Festivo.
        /// </summary>
        public static string Festivo
        {
            get
            {
                return ResourceManager.GetString("Festivo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Forzar Cambio.
        /// </summary>
        public static string ForzarCambio
        {
            get
            {
                return ResourceManager.GetString("ForzarCambio", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Grupo ImaSoft RH.
        /// </summary>
        public static string GrupoImaSoftRH
        {
            get
            {
                return ResourceManager.GetString("GrupoImaSoftRH", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string General
        {
            get
            {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Grupo Sanguíneo.
        /// </summary>
        public static string GrupoSanguineo
        {
            get
            {
                return ResourceManager.GetString("GrupoSanguineo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Información.
        /// </summary>
        public static string GuardarInformacion
        {
            get
            {
                return ResourceManager.GetString("GuardarInformacion", resourceCulture);
            }
        }

        public static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        public static string Exito
        {
            get
            {
                return ResourceManager.GetString("Exito", resourceCulture);
            }
        }

        public static string EdicionEmpresa
        {
            get
            {
                return ResourceManager.GetString("EdicionEmpresa", resourceCulture);
            }
        }

        public static string EdicionConfiguracionPassword
        {
            get
            {
                return ResourceManager.GetString("EdicionConfiguracionPassword", resourceCulture);
            }
        }

        public static string EdicionConfiguracionSmtp
        {
            get
            {
                return ResourceManager.GetString("EdicionConfiguracionSmtp", resourceCulture);
            }
        }

        public static string EdicionEntidadFinanciera
        {
            get
            {
                return ResourceManager.GetString("EdicionEntidadFinanciera", resourceCulture);
            }
        }

        public static string ExisteEntidadMarcadaComoPrincipal
        {
            get
            {
                return ResourceManager.GetString("ExisteEntidadMarcadaComoPrincipal", resourceCulture);
            }
        }

        public static string EmpresaSeEncuentraConfigurado
        {
            get
            {
                return ResourceManager.GetString("EmpresaSeEncuentraConfigurado", resourceCulture);
            }
        }

        public static string FormaPago
        {
            get
            {
                return ResourceManager.GetString("FormaPago", resourceCulture);
            }
        }

        public static string Departamento
        {
            get
            {
                return ResourceManager.GetString("Departamento", resourceCulture);
            }
        }

        public static string Dias
        {
            get
            {
                return ResourceManager.GetString("Dias", resourceCulture);
            }
        }

        public static string FechaIngreso
        {
            get
            {
                return ResourceManager.GetString("FechaIngreso", resourceCulture);
            }
        }

        public static string EmailExiste
        {
            get
            {
                return ResourceManager.GetString("EmailExiste", resourceCulture);
            }
        }

        public static string DatosPersonales
        {
            get
            {
                return ResourceManager.GetString("DatosPersonales", resourceCulture);
            }
        }

        public static string DatosEmpresa
        {
            get
            {
                return ResourceManager.GetString("DatosEmpresa", resourceCulture);
            }
        }

        public static string DatosAcademicos
        {
            get
            {
                return ResourceManager.GetString("DatosAcademicos", resourceCulture);
            }
        }

        public static string DatosFamiliares
        {
            get
            {
                return ResourceManager.GetString("DatosFamiliares", resourceCulture);
            }
        }

        public static string GradoAcademico
        {
            get
            {
                return ResourceManager.GetString("GradoAcademico", resourceCulture);
            }
        }

        public static string FechaMatrimonio
        {
            get
            {
                return ResourceManager.GetString("FechaMatrimonio", resourceCulture);
            }
        }

        public static string FechaCese
        {
            get
            {
                return ResourceManager.GetString("FechaCese", resourceCulture);
            }
        }

        public static string DescripcionCese
        {
            get
            {
                return ResourceManager.GetString("DescripcionCese", resourceCulture);
            }
        }

        public static string EquipoSeguridad
        {
            get
            {
                return ResourceManager.GetString("EquipoSeguridad", resourceCulture);
            }
        }

        public static string FechaAFP
        {
            get
            {
                return ResourceManager.GetString("FechaAFP", resourceCulture);
            }
        }

        public static string EntidadFinancieraCTS
        {
            get
            {
                return ResourceManager.GetString("EntidadFinancieraCTS", resourceCulture);
            }
        }

        public static string DiasDerechoVacacional
        {
            get
            {
                return ResourceManager.GetString("DiasDerechoVacacional", resourceCulture);
            }
        }

        public static string Foto
        {
            get
            {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }

        public static string FechaNacimiento
        {
            get
            {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }

        public static string Edad
        {
            get
            {
                return ResourceManager.GetString("Edad", resourceCulture);
            }
        }

        public static string Genero
        {
            get
            {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }

        public static string FechaCorporacion
        {
            get
            {
                return ResourceManager.GetString("FechaCorporacion", resourceCulture);
            }
        }

        public static string DatosPuesto
        {
            get
            {
                return ResourceManager.GetString("DatosPuesto", resourceCulture);
            }
        }

        public static string FechaIngresoPuesto
        {
            get
            {
                return ResourceManager.GetString("FechaIngresoPuesto", resourceCulture);
            }
        }

        public static string FechaCambioPuesto
        {
            get
            {
                return ResourceManager.GetString("FechaCambioPuesto", resourceCulture);
            }
        }

        public static string FechaInicioSalario
        {
            get
            {
                return ResourceManager.GetString("FechaInicioSalario", resourceCulture);
            }
        }

        public static string FechaInicioContrato
        {
            get
            {
                return ResourceManager.GetString("FechaInicioContrato", resourceCulture);
            }
        }

        public static string FechaFinContrato
        {
            get
            {
                return ResourceManager.GetString("FechaFinContrato", resourceCulture);
            }
        }

        public static string FechaFinSalario
        {
            get
            {
                return ResourceManager.GetString("FechaFinSalario", resourceCulture);
            }
        }

        public static string Descargar
        {
            get
            {
                return ResourceManager.GetString("Descargar", resourceCulture);
            }
        }

        public static string Entrar
        {
            get
            {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }

        public static string Descanso
        {
            get
            {
                return ResourceManager.GetString("Descanso", resourceCulture);
            }
        }

        public static string FinDescanso
        {
            get
            {
                return ResourceManager.GetString("FinDescanso", resourceCulture);
            }
        }

        public static string Fecha
        {
            get
            {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }

        public static string ErrorSeEncuentraEnUso
        {
            get
            {
                return ResourceManager.GetString("ErrorSeEncuentraEnUso", resourceCulture);
            }
        }


        public static string Formulario
        {
            get
            {
                return ResourceManager.GetString("Formulario", resourceCulture);
            }
        }

        public static string FlujosAprobacion
        {
            get
            {
                return ResourceManager.GetString("FlujosAprobacion", resourceCulture);
            }
        }

        public static string ExcepcionEnFlujo
        {
            get
            {
                return ResourceManager.GetString("ExcepcionEnFlujo", resourceCulture);
            }
        }

        public static string FlujoDeAprobacion
        {
            get
            {
                return ResourceManager.GetString("FlujoDeAprobacion", resourceCulture);
            }
        }

        public static string ExcepcionEnPasos
        {
            get
            {
                return ResourceManager.GetString("ExcepcionEnPasos", resourceCulture);
            }
        }

        public static string EnviarEmailSolicitante
        {
            get
            {
                return ResourceManager.GetString("EnviarEmailSolicitante", resourceCulture);
            }
        }

        public static string EnviarEmailAprobador
        {
            get
            {
                return ResourceManager.GetString("EnviarEmailAprobador", resourceCulture);
            }
        }

        public static string EnviarEmailAlFinalizar
        {
            get
            {
                return ResourceManager.GetString("EnviarEmailAlFinalizar", resourceCulture);
            }
        }

        public static string DiasMinimoASolicitar
        {
            get
            {
                return ResourceManager.GetString("DiasMinimoASolicitar", resourceCulture);
            }
        }

        public static string DiasMaximoASolicitar
        {
            get
            {
                return ResourceManager.GetString("DiasMaximoASolicitar", resourceCulture);
            }
        }

        public static string DiaInicialDelMes
        {
            get
            {
                return ResourceManager.GetString("DiaInicialDelMes", resourceCulture);
            }
        }

        public static string DiaFinalDelMes
        {
            get
            {
                return ResourceManager.GetString("DiaFinalDelMes", resourceCulture);
            }
        }

        public static string DiasAntelacion
        {
            get
            {
                return ResourceManager.GetString("DiasAntelacion", resourceCulture);
            }
        }

        public static string DiasPlazoAprobacion
        {
            get
            {
                return ResourceManager.GetString("DiasPlazoAprobacion", resourceCulture);
            }
        }

        public static string DiasMinimoAAprobar
        {
            get
            {
                return ResourceManager.GetString("DiasMinimoAAprobar", resourceCulture);
            }
        }

        public static string DiasMaximoAAprobar
        {
            get
            {
                return ResourceManager.GetString("DiasMaximoAAprobar", resourceCulture);
            }
        }

        public static string Guardar
        {
            get
            {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }

        public static string GuardarNuevo
        {
            get
            {
                return ResourceManager.GetString("GuardarNuevo", resourceCulture);
            }
        }

        public static string GuardarCerrar
        {
            get
            {
                return ResourceManager.GetString("GuardarCerrar", resourceCulture);
            }
        }

        public static string FlujosConfigurados
        {
            get
            {
                return ResourceManager.GetString("FlujosConfigurados", resourceCulture);
            }
        }

        public static string FlujosNoConfigurados
        {
            get
            {
                return ResourceManager.GetString("FlujosNoConfigurados", resourceCulture);
            }
        }

        public static string FechaInicioAusentismo
        {
            get
            {
                return ResourceManager.GetString("FechaInicioAusentismo", resourceCulture);
            }
        }

        public static string FechaFinAusentismo
        {
            get
            {
                return ResourceManager.GetString("FechaFinAusentismo", resourceCulture);
            }
        }

        public static string FechaInicioNoPuedeSerMayorAFechaFin
        {
            get
            {
                return ResourceManager.GetString("FechaInicioNoPuedeSerMayorAFechaFin", resourceCulture);
            }
        }

        public static string ExisteCruceDeFechasConOtroAusentismoParaElUsuario
        {
            get
            {
                return ResourceManager.GetString("ExisteCruceDeFechasConOtroAusentismoParaElUsuario", resourceCulture);
            }
        }

        public static string ElUsuarioSeEncuentraAusenteNoPuedeSerReemplazante
        {
            get
            {
                return ResourceManager.GetString("ElUsuarioSeEncuentraAusenteNoPuedeSerReemplazante", resourceCulture);
            }
        }

        public static string ElUsuarioNoPuedeEstarAusentePorqueEstaConfirguradoComoReemplazante
        {
            get
            {
                return ResourceManager.GetString("ElUsuarioNoPuedeEstarAusentePorqueEstaConfirguradoComoReemplazante", resourceCulture);
            }
        }

        public static string Generar
        {
            get
            {
                return ResourceManager.GetString("Generar", resourceCulture);
            }
        }

        public static string DocumentoElectronicos
        {
            get
            {
                return ResourceManager.GetString("DocumentoElectronicos", resourceCulture);
            }
        }
        public static string FechaFin
        {
            get
            {
                return ResourceManager.GetString("FechaFin", resourceCulture);
            }
        }
        public static string Defecto
        {
            get
            {
                return ResourceManager.GetString("Defecto", resourceCulture);
            }
        }

        public static string DatosJuridicos
        {
            get
            {
                return ResourceManager.GetString("DatosJuridicos", resourceCulture);
            }
        }

        public static string FormulariosPersonalizables
        {
            get
            {
                return ResourceManager.GetString("FormulariosPersonalizables", resourceCulture);
            }
        }

        public static string Formularios
        {
            get
            {
                return ResourceManager.GetString("Formularios", resourceCulture);
            }
        }

        public static string Grid
        {
            get
            {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }

        public static string Etiqueta
        {
            get
            {
                return ResourceManager.GetString("Etiqueta", resourceCulture);
            }
        }

        public static string FormulariosNuevos
        {
            get
            {
                return ResourceManager.GetString("FormulariosNuevos", resourceCulture);
            }
        }

        public static string DatosAdicionales
        {
            get
            {
                return ResourceManager.GetString("DatosAdicionales", resourceCulture);
            }
        }

        public static string EdicionDatos
        {
            get
            {
                return ResourceManager.GetString("EdicionDatos", resourceCulture);
            }
        }

        public static string EmpleadoBaja
        {
            get
            {
                return ResourceManager.GetString("EmpleadoBaja", resourceCulture);
            }
        }

        public static string DocumentoElectronicosOtros
        {
            get
            {
                return ResourceManager.GetString("DocumentoElectronicosOtros", resourceCulture);
            }
        }

        public static string Dato
        {
            get
            {
                return ResourceManager.GetString("Dato", resourceCulture);
            }
        }

        public static string DiasLaborales
        {
            get
            {
                return ResourceManager.GetString("DiasLaborales", resourceCulture);
            }
        }

        public static string Formulacion
        {
            get
            {
                return ResourceManager.GetString("Formulacion", resourceCulture);
            }
        }

        public static string DebeSelecCfgVaca
        {
            get
            {
                return ResourceManager.GetString("DebeSelecCfgVaca", resourceCulture);
            }
        }

        public static string EmpleadosAsignados
        {
            get
            {
                return ResourceManager.GetString("EmpleadosAsignados", resourceCulture);
            }
        }

        public static string GridNoSeleccion
        {
            get
            {
                return ResourceManager.GetString("GridNoSeleccion", resourceCulture);
            }
        }

        public static string GenerarSolicitud
        {
            get
            {
                return ResourceManager.GetString("GenerarSolicitud", resourceCulture);
            }
        }

        public static string Generador
        {
            get
            {
                return ResourceManager.GetString("Generador", resourceCulture);
            }
        }

        public static string GeneradorReporte
        {
            get
            {
                return ResourceManager.GetString("GeneradorReporte", resourceCulture);
            }
        }

        public static string DatosReporte
        {
            get
            {
                return ResourceManager.GetString("DatosReporte", resourceCulture);
            }
        }

        public static string Gestion
        {
            get
            {
                return ResourceManager.GetString("Gestion", resourceCulture);
            }
        }

        public static string Detalle
        {
            get
            {
                return ResourceManager.GetString("Detalle", resourceCulture);
            }
        }

        public static string Desaprobar
        {
            get
            {
                return ResourceManager.GetString("Desaprobar", resourceCulture);
            }
        }

        public static string DetalleVacaciones
        {
            get
            {
                return ResourceManager.GetString("DetalleVacaciones", resourceCulture);
            }
        }
        

        public static string DiasDinero
        {
            get
            {
                return ResourceManager.GetString("DiasDinero", resourceCulture);
            }
        }
        
    }
}
