//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTelerik.Resources
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_ABC
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_ABC()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoTelerik.Resources.Resource_ABC", typeof(Resource_ABC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Abreviatura.
        /// </summary>
        public static string Abreviatura
        {
            get
            {
                return ResourceManager.GetString("Abreviatura", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string Accion
        {
            get
            {
                return ResourceManager.GetString("Accion", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Añadir.
        /// </summary>
        public static string Anadir
        {
            get
            {
                return ResourceManager.GetString("Anadir", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Aprobación Solicitud.
        /// </summary>
        public static string AprobacionSolicitud
        {
            get
            {
                return ResourceManager.GetString("AprobacionSolicitud", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Asignar Permisos.
        /// </summary>
        public static string AsignarPermisos
        {
            get
            {
                return ResourceManager.GetString("AsignarPermisos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Asignar Usuarios.
        /// </summary>
        public static string AsignarUsuarios
        {
            get
            {
                return ResourceManager.GetString("AsignarUsuarios", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Asunto Solicitud.
        ///   Busca una cadena traducida similar a Asunto Solicitud.
        /// </summary>
        public static string AsuntoSolicitud
        {
            get
            {
                return ResourceManager.GetString("AsuntoSolicitud", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Creado por: {0} - {1} | Modificado por: {2} - {3}.
        /// </summary>
        public static string Auditoria
        {
            get
            {
                return ResourceManager.GetString("Auditoria", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca Festivo.
        /// </summary>
        public static string BibliotecaFestivo
        {
            get
            {
                return ResourceManager.GetString("BibliotecaFestivo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar mi contraseña.
        /// </summary>
        public static string CambiarMiContrasena
        {
            get
            {
                return ResourceManager.GetString("CambiarMiContrasena", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Carga Masiva.
        /// </summary>
        public static string CargaMasiva
        {
            get
            {
                return ResourceManager.GetString("CargaMasiva", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string CerrarSesion
        {
            get
            {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string Codigo
        {
            get
            {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código AFPnet.
        /// </summary>
        public static string CodigoAfpNet
        {
            get
            {
                return ResourceManager.GetString("CodigoAfpNet", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código Empleado Digitado.
        /// </summary>
        public static string CodigoEmpleadoDigitado
        {
            get
            {
                return ResourceManager.GetString("CodigoEmpleadoDigitado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código ISO.
        /// </summary>
        public static string CodigoIso
        {
            get
            {
                return ResourceManager.GetString("CodigoIso", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        public static string CodigoPostal
        {
            get
            {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Código Sunat.
        /// </summary>
        public static string CodigoSunat
        {
            get
            {
                return ResourceManager.GetString("CodigoSunat", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Color Empresa.
        /// </summary>
        public static string ColorEmpresa
        {
            get
            {
                return ResourceManager.GetString("ColorEmpresa", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Complete los campos obligatorios..
        /// </summary>
        public static string CompleteLosCamposObligatorios
        {
            get
            {
                return ResourceManager.GetString("CompleteLosCamposObligatorios", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones.
        /// </summary>
        public static string Configuraciones
        {
            get
            {
                return ResourceManager.GetString("Configuraciones", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones Empresa.
        /// </summary>
        public static string ConfiguracionesEmpresa
        {
            get
            {
                return ResourceManager.GetString("ConfiguracionesEmpresa", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Confirma tu contraseña.
        /// </summary>
        public static string ConfirmaTuContrasena
        {
            get
            {
                return ResourceManager.GetString("ConfirmaTuContrasena", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contrasena
        {
            get
            {
                return ResourceManager.GetString("Contrasena", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Controlador.
        /// </summary>
        public static string Controlador
        {
            get
            {
                return ResourceManager.GetString("Controlador", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string CorreoElectronico
        {
            get
            {
                return ResourceManager.GetString("CorreoElectronico", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cuerpo Aprobacion Solicitud.
        /// </summary>
        public static string CuerpoAprobacionSolicitud
        {
            get
            {
                return ResourceManager.GetString("CuerpoAprobacionSolicitud", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cuerpo Solicitud.
        /// </summary>
        public static string CuerpoSolicitud
        {
            get
            {
                return ResourceManager.GetString("CuerpoSolicitud", resourceCulture);
            }
        }

        public static string CambioDeContrasena
        {
            get
            {
                return ResourceManager.GetString("CambioDeContrasena", resourceCulture);
            }
        }

        public static string Configuracion
        {
            get
            {
                return ResourceManager.GetString("Configuracion", resourceCulture);
            }
        }

        public static string ConfiguracionPassword
        {
            get
            {
                return ResourceManager.GetString("ConfiguracionPassword", resourceCulture);
            }
        }

        public static string ConfiguracionSmtp
        {
            get
            {
                return ResourceManager.GetString("ConfiguracionSmtp", resourceCulture);
            }
        }

        public static string Cts
        {
            get
            {
                return ResourceManager.GetString("Cts", resourceCulture);
            }
        }

        public static string CentroCosto
        {
            get
            {
                return ResourceManager.GetString("CentroCosto", resourceCulture);
            }
        }

        public static string Area
        {
            get
            {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }

        public static string Colaboradores
        {
            get
            {
                return ResourceManager.GetString("Colaboradores", resourceCulture);
            }
        }

        public static string Apellidos
        {
            get
            {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }

        public static string CodigoDeEmpleadoExiste
        {
            get
            {
                return ResourceManager.GetString("CodigoDeEmpleadoExiste", resourceCulture);
            }
        }

        public static string CantidadDependientes
        {
            get
            {
                return ResourceManager.GetString("CantidadDependientes", resourceCulture);
            }
        }

        public static string CodigoEmpleado
        {
            get
            {
                return ResourceManager.GetString("CodigoEmpleado", resourceCulture);
            }
        }

        public static string BibliotecaFestivos
        {
            get
            {
                return ResourceManager.GetString("BibliotecaFestivos", resourceCulture);
            }
        }

        public static string BajaEmpleado
        {
            get
            {
                return ResourceManager.GetString("BajaEmpleado", resourceCulture);
            }
        }

        public static string CambioPuesto
        {
            get
            {
                return ResourceManager.GetString("CambioPuesto", resourceCulture);
            }
        }

        public static string Contrato
        {
            get
            {
                return ResourceManager.GetString("Contrato", resourceCulture);
            }
        }

        public static string CambioEstructura
        {
            get
            {
                return ResourceManager.GetString("CambioEstructura", resourceCulture);
            }
        }

        public static string CambioSalario
        {
            get
            {
                return ResourceManager.GetString("CambioSalario", resourceCulture);
            }
        }

        public static string CambioContrato
        {
            get
            {
                return ResourceManager.GetString("CambioContrato", resourceCulture);
            }
        }

        public static string Calendario
        {
            get
            {
                return ResourceManager.GetString("Calendario", resourceCulture);
            }
        }

        public static string Color
        {
            get
            {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }


        public static string ConfigurarFlujo
        {
            get
            {
                return ResourceManager.GetString("ConfigurarFlujo", resourceCulture);
            }
        }

        public static string Aprobaciones
        {
            get
            {
                return ResourceManager.GetString("Aprobaciones", resourceCulture);
            }
        }

        public static string CopiarFlujo
        {
            get
            {
                return ResourceManager.GetString("CopiarFlujo", resourceCulture);
            }
        }

        public static string AnadirNuevoPaso
        {
            get
            {
                return ResourceManager.GetString("AnadirNuevoPaso", resourceCulture);
            }
        }

        public static string Anno
        {
            get
            {
                return ResourceManager.GetString("Anno", resourceCulture);
            }
        }

        

        public static string Ausentismo
        {
            get
            {
                return ResourceManager.GetString("Ausentismo", resourceCulture);
            }
        }

        public static string ActivarAusentismo
        {
            get
            {
                return ResourceManager.GetString("ActivarAusentismo", resourceCulture);
            }
        }

        public static string ColorTablas
        {
            get
            {
                return ResourceManager.GetString("ColorTablas", resourceCulture);
            }
        }
        
        public static string BoletaPago
        {
            get
            {
                return ResourceManager.GetString("BoletaPago", resourceCulture);
            }
        }

        public static string CertificadoTrabajo
        {
            get
            {
                return ResourceManager.GetString("CertificadoTrabajo", resourceCulture);
            }
        }

        public static string CertificadoQuinta
        {
            get
            {
                return ResourceManager.GetString("CertificadoQuinta", resourceCulture);
            }
        }

        public static string ConstanciaCese
        {
            get
            {
                return ResourceManager.GetString("ConstanciaCese", resourceCulture);
            }
        }
        
        public static string Claro
        {
            get
            {
                return ResourceManager.GetString("Claro", resourceCulture);
            }
        }
        
        public static string CopiarFormulario
        {
            get
            {
                return ResourceManager.GetString("CopiarFormulario", resourceCulture);
            }
        }
        
        public static string CamposConfigurados
        {
            get
            {
                return ResourceManager.GetString("CamposConfigurados", resourceCulture);
            }
        }
        
        public static string Campo
        {
            get
            {
                return ResourceManager.GetString("Campo", resourceCulture);
            }
        }
        
        public static string AnadirNuevoCampo
        {
            get
            {
                return ResourceManager.GetString("AnadirNuevoCampo", resourceCulture);
            }
        }
        
        public static string AnadirValores
        {
            get
            {
                return ResourceManager.GetString("AnadirValores", resourceCulture);
            }
        }
        public static string Archivo
        {
            get
            {
                return ResourceManager.GetString("Archivo", resourceCulture);
            }
        }

        public static string AsignarFlujos
        {
            get
            {
                return ResourceManager.GetString("AsignarFlujos", resourceCulture);
            }
        }

        public static string ContrasenaAnterior
        {
            get
            {
                return ResourceManager.GetString("ContrasenaAnterior", resourceCulture);
            }
        }

        public static string ContrasenaNueva
        {
            get
            {
                return ResourceManager.GetString("ContrasenaNueva", resourceCulture);
            }
        }

        public static string Consideracion
        {
            get
            {
                return ResourceManager.GetString("Consideracion", resourceCulture);
            }
        }

        public static string ConfiguracionVacaciones
        {
            get
            {
                return ResourceManager.GetString("ConfiguracionVacaciones", resourceCulture);
            }
        }

        public static string Activo
        {
            get
            {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }

        public static string Acumulacion
        {
            get
            {
                return ResourceManager.GetString("Acumulacion", resourceCulture);
            }
        }

        public static string CantidadDias
        {
            get
            {
                return ResourceManager.GetString("CantidadDias", resourceCulture);
            }
        }

        public static string AsignarVacaciones
        {
            get
            {
                return ResourceManager.GetString("AsignarVacaciones", resourceCulture);
            }
        }
        public static string Aprobar
        {
            get
            {
                return ResourceManager.GetString("Aprobar", resourceCulture);
            }
        }
        
    }
}
