//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTelerik.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_HIJKLM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_HIJKLM() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoTelerik.Resources.Resource_HIJKLM", typeof(Resource_HIJKLM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacer el cambio de contraseña.
        /// </summary>
        public static string HacerElCambioDeContrasena {
            get {
                return ResourceManager.GetString("HacerElCambioDeContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemos enviado a tu correo &lt;b&gt;{0}&lt;/b&gt; las instrucciones para cambiar tu contraseña..
        /// </summary>
        public static string HemosEnviandoATuCorreoLasInstrucciones {
            get {
                return ResourceManager.GetString("HemosEnviandoATuCorreoLasInstrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ícono.
        /// </summary>
        public static string Icono {
            get {
                return ResourceManager.GetString("Icono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Empleado.
        /// </summary>
        public static string IdEstadoEmpleado {
            get {
                return ResourceManager.GetString("IdEstadoEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda Base.
        /// </summary>
        public static string IdMonedaBase {
            get {
                return ResourceManager.GetString("IdMonedaBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda Cambio.
        /// </summary>
        public static string IdMonedaCambio {
            get {
                return ResourceManager.GetString("IdMonedaCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Cambio.
        /// </summary>
        public static string IdTipoCambio {
            get {
                return ResourceManager.GetString("IdTipoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir Mayúscula.
        /// </summary>
        public static string IncluirMayuscula {
            get {
                return ResourceManager.GetString("IncluirMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir Número.
        /// </summary>
        public static string IncluirNumero {
            get {
                return ResourceManager.GetString("IncluirNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir Símbolo.
        /// </summary>
        public static string IncluirSimbolo {
            get {
                return ResourceManager.GetString("IncluirSimbolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar el usuario..
        /// </summary>
        public static string IngresarElUsuario {
            get {
                return ResourceManager.GetString("IngresarElUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar la contraseña..
        /// </summary>
        public static string IngresarLaContrasena {
            get {
                return ResourceManager.GetString("IngresarLaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jefe Directo.
        /// </summary>
        public static string JefeDirecto {
            get {
                return ResourceManager.GetString("JefeDirecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencia incorrecta..
        /// </summary>
        public static string LicenciaIncorrecta {
            get {
                return ResourceManager.GetString("LicenciaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud Mínima.
        /// </summary>
        public static string LongitudMinima {
            get {
                return ResourceManager.GetString("LongitudMinima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos ingresados no coinciden..
        /// </summary>
        public static string LosDatosIngresadosNoCoinciden {
            get {
                return ResourceManager.GetString("LosDatosIngresadosNoCoinciden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento.
        /// </summary>
        public static string Mantenimiento
        {
            get
            {
                return ResourceManager.GetString("Mantenimiento", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menú.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutos ajustados.
        /// </summary>
        public static string MinutosAjustados {
            get {
                return ResourceManager.GetString("MinutosAjustados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misión.
        /// </summary>
        public static string Mision {
            get {
                return ResourceManager.GetString("Mision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misión/Visión/Valores.
        /// </summary>
        public static string MisionVisionValores {
            get {
                return ResourceManager.GetString("MisionVisionValores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        public static string Modulo {
            get {
                return ResourceManager.GetString("Modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda.
        /// </summary>
        public static string Moneda {
            get {
                return ResourceManager.GetString("Moneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipio.
        /// </summary>
        public static string Municipio {
            get {
                return ResourceManager.GetString("Municipio", resourceCulture);
            }
        }

        public static string MenuCampo
        {
            get {
                return ResourceManager.GetString("MenuCampo", resourceCulture);
            }
        }

        public static string LasContrasenasNoCoinciden
        {
            get {
                return ResourceManager.GetString("LasContrasenasNoCoinciden", resourceCulture);
            }
        }

        public static string LogoMenu
        {
            get {
                return ResourceManager.GetString("LogoMenu", resourceCulture);
            }
        }

        public static string MotivoCambioPuesto
        {
            get {
                return ResourceManager.GetString("MotivoCambioPuesto", resourceCulture);
            }
        }

        public static string MonedaCTS
        {
            get {
                return ResourceManager.GetString("MonedaCTS", resourceCulture);
            }
        }

        public static string Jefe
        {
            get {
                return ResourceManager.GetString("Jefe", resourceCulture);
            }
        }

        public static string HistoricoPuestos
        {
            get {
                return ResourceManager.GetString("HistoricoPuestos", resourceCulture);
            }
        }

        public static string HistoricoSalario
        {
            get {
                return ResourceManager.GetString("HistoricoSalario", resourceCulture);
            }
        }

        public static string HistoricoContrato
        {
            get {
                return ResourceManager.GetString("HistoricoContrato", resourceCulture);
            }
        }

        public static string Jornada
        {
            get {
                return ResourceManager.GetString("Jornada", resourceCulture);
            }
        }

        public static string Marcacion
        {
            get {
                return ResourceManager.GetString("Marcacion", resourceCulture);
            }
        }

        public static string HoraInicio
        {
            get {
                return ResourceManager.GetString("HoraInicio", resourceCulture);
            }
        }

        public static string HoraFin
        {
            get {
                return ResourceManager.GetString("HoraFin", resourceCulture);
            }
        }

        public static string MarcacionEmpleados
        {
            get {
                return ResourceManager.GetString("MarcacionEmpleados", resourceCulture);
            }
        }

        public static string InactivarAusentismo
        {
            get {
                return ResourceManager.GetString("InactivarAusentismo", resourceCulture);
            }
        }

        public static string MenuSuperior
        {
            get {
                return ResourceManager.GetString("MenuSuperior", resourceCulture);
            }
        }

        public static string ModosDeTema
        {
            get {
                return ResourceManager.GetString("ModosDeTema", resourceCulture);
            }
        }

        public static string ModoPorDefecto
        {
            get {
                return ResourceManager.GetString("ModoPorDefecto", resourceCulture);
            }
        }

        public static string ModoClaro
        {
            get {
                return ResourceManager.GetString("ModoClaro", resourceCulture);
            }
        }
        public static string LBS
        {
            get
            {
                return ResourceManager.GetString("LBS", resourceCulture);
            }
        }

        public static string ModoOscuro
        {
            get {
                return ResourceManager.GetString("ModoOscuro", resourceCulture);
            }
        }

        public static string MisDocumentos
        {
            get
            {
                return ResourceManager.GetString("MisDocumentos", resourceCulture);
            }
        }

        public static string MinimoMeses
        {
            get
            {
                return ResourceManager.GetString("MinimoMeses", resourceCulture);
            }
        }

        public static string MaximoMeses
        {
            get
            {
                return ResourceManager.GetString("MaximoMeses", resourceCulture);
            }
        }

        public static string Individual
        {
            get
            {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }

        public static string MiPerfil
        {
            get
            {
                return ResourceManager.GetString("MiPerfil", resourceCulture);
            }
        }

        public static string MisProcesos
        {
            get
            {
                return ResourceManager.GetString("MisProcesos", resourceCulture);
            }
        }

        public static string MisSolicitudes
        {
            get
            {
                return ResourceManager.GetString("MisSolicitudes", resourceCulture);
            }
        }

        public static string HistoricoSolicitudes
        {
            get
            {
                return ResourceManager.GetString("HistoricoSolicitudes", resourceCulture);
            }
        }
        
    }
}
