//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTelerik.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_QRSTU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_QRSTU() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoTelerik.Resources.Resource_QRSTU", typeof(Resource_QRSTU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazo Solicitud.
        /// </summary>
        public static string RechazoSolicitud {
            get {
                return ResourceManager.GetString("RechazoSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar a inicio de sesión.
        /// </summary>
        public static string RegresarAInicioDeSesion {
            get {
                return ResourceManager.GetString("RegresarAInicioDeSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruc.
        /// </summary>
        public static string Ruc {
            get {
                return ResourceManager.GetString("Ruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizó correctamente..
        /// </summary>
        public static string SeActualizoCorrectamente {
            get {
                return ResourceManager.GetString("SeActualizoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminó correctamente..
        /// </summary>
        public static string SeEliminoCorrectamente {
            get {
                return ResourceManager.GetString("SeEliminoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha cambiado la contraseña..
        /// </summary>
        public static string SeHaCambiadoLaContrasena {
            get {
                return ResourceManager.GetString("SeHaCambiadoLaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviando un enlace correctamente a tu correo..
        /// </summary>
        public static string SeHaEnviandoUnEnlaceCorrectamenteATuCorreo {
            get {
                return ResourceManager.GetString("SeHaEnviandoUnEnlaceCorrectamenteATuCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error.
        /// </summary>
        public static string SeHaProducidoUnError {
            get {
                return ResourceManager.GetString("SeHaProducidoUnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar imagen.
        /// </summary>
        public static string SeleccionarImagen {
            get {
                return ResourceManager.GetString("SeleccionarImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione.
        /// </summary>
        public static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se registró correctamente..
        /// </summary>
        public static string SeRegistroCorrectamente {
            get {
                return ResourceManager.GetString("SeRegistroCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Símbolo.
        /// </summary>
        public static string Simbolo {
            get {
                return ResourceManager.GetString("Simbolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Smtp.
        /// </summary>
        public static string SMTP {
            get {
                return ResourceManager.GetString("SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud.
        /// </summary>
        public static string Solicitud {
            get {
                return ResourceManager.GetString("Solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Cambio Contraseña.
        /// </summary>
        public static string SolicitudCambioPassword {
            get {
                return ResourceManager.GetString("SolicitudCambioPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud Usuario Nuevo.
        /// </summary>
        public static string SolicitudUsuarioNuevo {
            get {
                return ResourceManager.GetString("SolicitudUsuarioNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo se puede seleccionar.
        /// </summary>
        public static string SoloSePuedeSeleccionar {
            get {
                return ResourceManager.GetString("SoloSePuedeSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ssl.
        /// </summary>
        public static string SSL {
            get {
                return ResourceManager.GetString("SSL", resourceCulture);
            }
        }



        public static string TabOpcion
        {
            get
            {
                return ResourceManager.GetString("TabOpcion", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Te enviaremos un enlace a tu correo para que puedas cambiar la contraseña..
        /// </summary>
        public static string TeEnviaremosUnEnlaceATuCorreo {
            get {
                return ResourceManager.GetString("TeEnviaremosUnEnlaceATuCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono 1.
        /// </summary>
        public static string Telefono1 {
            get {
                return ResourceManager.GetString("Telefono1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono 2.
        /// </summary>
        public static string Telefono2 {
            get {
                return ResourceManager.GetString("Telefono2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Afp.
        /// </summary>
        public static string TipoAfp {
            get {
                return ResourceManager.GetString("TipoAfp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Campo.
        /// </summary>
        public static string TipoCambio
        {
            get
            {
                return ResourceManager.GetString("TipoCambio", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Campo.
        /// </summary>
        public static string TipoCampo {
            get {
                return ResourceManager.GetString("TipoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo casa.
        /// </summary>
        public static string TipoCasa {
            get {
                return ResourceManager.GetString("TipoCasa", resourceCulture);
            }
        }

        /// <summary>
        /// Busca una cadena traducida similar a TipoCuentaBancaria.
        /// </summary>
        public static string TipoCuentaBancaria
        {
            get
            {
                return ResourceManager.GetString("TipoCuentaBancaria", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Doc. Gerente General.
        /// </summary>
        public static string TipoDocGerenteGeneral {
            get {
                return ResourceManager.GetString("TipoDocGerenteGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Doc. Representante Legal.
        /// </summary>
        public static string TipoDocRepresentanteLegal {
            get {
                return ResourceManager.GetString("TipoDocRepresentanteLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo documento identidad.
        /// </summary>
        public static string TipoDocumentoIdentidad {
            get {
                return ResourceManager.GetString("TipoDocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Género.
        /// </summary>
        public static string TipoGenero {
            get {
                return ResourceManager.GetString("TipoGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo giro.
        /// </summary>
        public static string TipoGiro {
            get {
                return ResourceManager.GetString("TipoGiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Permiso Menú Campo.
        /// </summary>
        public static string TipoPermisoMenuCampo {
            get {
                return ResourceManager.GetString("TipoPermisoMenuCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo vias.
        /// </summary>
        public static string TipoVias {
            get {
                return ResourceManager.GetString("TipoVias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo zona.
        /// </summary>
        public static string TipoZona {
            get {
                return ResourceManager.GetString("TipoZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Unidad
        {
            get
            {
                return ResourceManager.GetString("Unidad", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string UbicacionGeografica
        {
            get
            {
                return ResourceManager.GetString("UbicacionGeografica", resourceCulture);
            }
        }
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no existe o se encuentra bloqueado..
        /// </summary>
        public static string UsuarioNoExisteOSeEncuentraBloqueado {
            get {
                return ResourceManager.GetString("UsuarioNoExisteOSeEncuentraBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectas..
        /// </summary>
        public static string UsuarioOContrasenaIncorrectas {
            get {
                return ResourceManager.GetString("UsuarioOContrasenaIncorrectas", resourceCulture);
            }
        }

        public static string Seguridad
        {
            get {
                return ResourceManager.GetString("Seguridad", resourceCulture);
            }
        }

        public static string Roles
        {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }

        public static string Recomendado
        {
            get {
                return ResourceManager.GetString("Recomendado", resourceCulture);
            }
        }

        public static string TipoInstruccion
        {
            get
            {
                return ResourceManager.GetString("TipoInstruccion", resourceCulture);
            }
        }

        public static string TipoPariente
        {
            get
            {
                return ResourceManager.GetString("TipoPariente", resourceCulture);
            }
        }

        public static string TipoLicencia
        {
            get
            {
                return ResourceManager.GetString("TipoLicencia", resourceCulture);
            }
        }
        public static string TipoMotivoCese
        {
            get
            {
                return ResourceManager.GetString("TipoMotivoCese", resourceCulture);
            }
        }

        public static string TipoIngresoEmpresa
        {
            get
            {
                return ResourceManager.GetString("TipoIngresoEmpresa", resourceCulture);
            }
        }

        public static string TipoPlanilla
        {
            get
            {
                return ResourceManager.GetString("TipoPlanilla", resourceCulture);
            }
        }
        public static string Utilidades
        {
            get
            {
                return ResourceManager.GetString("Utilidades", resourceCulture);
            }
        }
        

        public static string Seccion
        {
            get
            {
                return ResourceManager.GetString("Seccion", resourceCulture);
            }
        }

        public static string TipoContrato
        {
            get
            {
                return ResourceManager.GetString("TipoContrato", resourceCulture);
            }
        }

        public static string SeHaDadoDeBajaCorrectamente
        {
            get
            {
                return ResourceManager.GetString("SeHaDadoDeBajaCorrectamente", resourceCulture);
            }
        }

        public static string Telefono3
        {
            get
            {
                return ResourceManager.GetString("Telefono3", resourceCulture);
            }
        }

        public static string Ubicacion1
        {
            get
            {
                return ResourceManager.GetString("Ubicacion1", resourceCulture);
            }
        }

        public static string Ubicacion2
        {
            get
            {
                return ResourceManager.GetString("Ubicacion2", resourceCulture);
            }
        }

        public static string TipoIngreso
        {
            get
            {
                return ResourceManager.GetString("TipoIngreso", resourceCulture);
            }
        }

        public static string Sueldo
        {
            get
            {
                return ResourceManager.GetString("Sueldo", resourceCulture);
            }
        }

        public static string SegundoApellido
        {
            get
            {
                return ResourceManager.GetString("SegundoApellido", resourceCulture);
            }
        }

        public static string UbigueoNacimiento
        {
            get
            {
                return ResourceManager.GetString("UbigueoNacimiento", resourceCulture);
            }
        }

        public static string UbigueoResidencia
        {
            get
            {
                return ResourceManager.GetString("UbigueoResidencia", resourceCulture);
            }
        }

        public static string TipoSeguro
        {
            get
            {
                return ResourceManager.GetString("TipoSeguro", resourceCulture);
            }
        }

        public static string SeHaCambiadoDePuestoCorrectamente
        {
            get
            {
                return ResourceManager.GetString("SeHaCambiadoDePuestoCorrectamente", resourceCulture);
            }
        }

        public static string Ubicacion
        {
            get
            {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }

        public static string Salarial
        {
            get
            {
                return ResourceManager.GetString("Salarial", resourceCulture);
            }
        }

        public static string SeleccionarArchivo
        {
            get
            {
                return ResourceManager.GetString("SeleccionarArchivo", resourceCulture);
            }
        }

        public static string SeHaCambiadoDeContratoCorrectamente
        {
            get
            {
                return ResourceManager.GetString("SeHaCambiadoDeContratoCorrectamente", resourceCulture);
            }
        }

        public static string SeHaCambiadoDeSalarioCorrectamente
        {
            get
            {
                return ResourceManager.GetString("SeHaCambiadoDeSalarioCorrectamente", resourceCulture);
            }
        }

        public static string SeHaCambiadoDeEstructuraCorrectamente
        {
            get
            {
                return ResourceManager.GetString("SeHaCambiadoDeEstructuraCorrectamente", resourceCulture);
            }
        }

        public static string Salir
        {
            get
            {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }

        public static string TotalHoras
        {
            get
            {
                return ResourceManager.GetString("TotalHoras", resourceCulture);
            }
        }

        public static string ReenviarDesaprobada
        {
            get
            {
                return ResourceManager.GetString("ReenviarDesaprobada", resourceCulture);
            }
        }

        public static string TipoAprobacion
        {
            get
            {
                return ResourceManager.GetString("TipoAprobacion", resourceCulture);
            }
        }

        public static string SeleccionarTipoAprobacion
        {
            get
            {
                return ResourceManager.GetString("SeleccionarTipoAprobacion", resourceCulture);
            }
        }

        public static string TipoExcepcion
        {
            get
            {
                return ResourceManager.GetString("TipoExcepcion", resourceCulture);
            }
        }

        public static string TipoConfiguracion
        {
            get
            {
                return ResourceManager.GetString("TipoConfiguracion", resourceCulture);
            }
        }

        public static string UsuarioOpcional
        {
            get
            {
                return ResourceManager.GetString("UsuarioOpcional", resourceCulture);
            }
        }

        public static string SeleccionePuesto
        {
            get
            {
                return ResourceManager.GetString("SeleccionePuesto", resourceCulture);
            }
        }

        public static string SeleccioneColaborador
        {
            get
            {
                return ResourceManager.GetString("SeleccioneColaborador", resourceCulture);
            }
        }

        public static string SeleccioneRol
        {
            get
            {
                return ResourceManager.GetString("SeleccioneRol", resourceCulture);
            }
        }

        public static string Reportes
        {
            get
            {
                return ResourceManager.GetString("Reportes", resourceCulture);
            }
        }

        public static string TabOpcionGenerarPdf
        {
            get
            {
                return ResourceManager.GetString("TabOpcionGenerarPdf", resourceCulture);
            }
        }

        public static string TipoReporte
        {
            get
            {
                return ResourceManager.GetString("TipoReporte", resourceCulture);
            }
        }

        public static string Sede
        {
            get
            {
                return ResourceManager.GetString("Sede", resourceCulture);
            }
        }
        public static string TipoTabla
        {
            get
            {
                return ResourceManager.GetString("TipoTabla", resourceCulture);
            }
        }
        


        public static string UsuarioAusente
        {
            get
            {
                return ResourceManager.GetString("UsuarioAusente", resourceCulture);
            }
        }

        public static string UsuarioReemplazante
        {
            get
            {
                return ResourceManager.GetString("UsuarioReemplazante", resourceCulture);
            }
        }

        public static string UsuarioReemplazanteNoPuedeSerIgual
        {
            get
            {
                return ResourceManager.GetString("UsuarioReemplazanteNoPuedeSerIgual", resourceCulture);
            }
        }

        public static string SeActivoCorrectamente
        {
            get
            {
                return ResourceManager.GetString("SeActivoCorrectamente", resourceCulture);
            }
        }

        public static string SeInactivoCorrectamente
        {
            get
            {
                return ResourceManager.GetString("SeInactivoCorrectamente", resourceCulture);
            }
        }

        public static string SolicitudesEstandar
        {
            get
            {
                return ResourceManager.GetString("SolicitudesEstandar", resourceCulture);
            }
        }
        public static string CaObligatoriosIncompletos
        {
            get
            {
                return ResourceManager.GetString("CaObligatoriosIncompletos", resourceCulture);
            }
        }
        public static string MeObligatoriosIncompletos
        {
            get
            {
                return ResourceManager.GetString("MeObligatoriosIncompletos", resourceCulture);
            }
        }
        public static string Reingreso
        {
            get
            {
                return ResourceManager.GetString("Reingreso", resourceCulture);
            }
        }
        public static string TabOpcionModificar
        {
            get
            {
                return ResourceManager.GetString("TabOpcionModificar", resourceCulture);
            }
        }

        public static string Todos
        {
            get
            {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }

        public static string TabOpcionSolicitudes
        {
            get
            {
                return ResourceManager.GetString("TabOpcionSolicitudes", resourceCulture);
            }
        }

        public static string RegistroSolicitud
        {
            get
            {
                return ResourceManager.GetString("RegistroSolicitud", resourceCulture);
            }
        }

        public static string TipoSolicitud
        {
            get
            {
                return ResourceManager.GetString("TipoSolicitud", resourceCulture);
            }
        }
        

        public static string SolicitudAprobacion
        {
            get
            {
                return ResourceManager.GetString("SolicitudAprobacion", resourceCulture);
            }
        }
    }
}
